<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Smart Iframe Loader</title>
  <style>
    body {
      font-family: sans-serif;
      padding: 20px;
      background: #f9f9f9;
    }
    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
      gap: 20px;
    }
    .box {
      background: #fff;
      padding: 10px;
      box-shadow: 0 0 8px rgba(0,0,0,0.1);
      border-radius: 10px;
      overflow: hidden;
    }
    iframe {
      width: 100%;
      height: 250px;
      border: none;
      margin-bottom: 10px;
      pointer-events: none; 
    }
  </style>
</head>
<body>

  <h2>Smart Auto-Loading Iframe Boxes</h2>
  <div class="grid" id="container">
    
  </div>

  <script>
    const iframeUrls = [
      "https://identifycertainlybookie.com/t9ecqs283?key=5b54e866a0852e162b008b39fca8278a",
      "https://identifycertainlybookie.com/zdrcg449?key=cf426edf30c54b3c4a0b6fe6c75825b4",
      "https://identifycertainlybookie.com/n5p706701h?key=43df0edd470783c8ea268afae3d4a3c8",
      "https://identifycertainlybookie.com/q185zipe8?key=3bb955f89241a80b82885ea94acdbae9",
      "https://identifycertainlybookie.com/zmvwpqim?key=7edabe4b052dc3549d5c3dc326db284a"
    ];

    function createBox(index) {
      const box = document.createElement('div');
      box.className = 'box';
      box.innerHTML = `<h4>Box ${index + 1}</h4>`;

      const shuffled = iframeUrls.sort(() => 0.5 - Math.random());
      for (let i = 0; i < 3; i++) {
        const iframe = document.createElement('iframe');
        iframe.dataset.src = shuffled[i % iframeUrls.length];
        box.appendChild(iframe);
      }
      return box;
    }

    function initBoxes() {
      const container = document.getElementById('container');
      for (let i = 0; i < 10; i++) {
        container.appendChild(createBox(i));
      }
    }

    function autoTriggerHoverScroll() {
      const iframes = document.querySelectorAll('iframe');
      let offset = 0;
      setInterval(() => {
        offset += 1;
        iframes.forEach(iframe => {
          try {
            const iframeDoc = iframe.contentWindow.document;
            iframe.contentWindow.scrollBy(0, offset % 100);
          } catch (e) {
           
          }
        });
      }, 3000);
    }

    function lazyLoadIframes() {
      const allIframes = document.querySelectorAll('iframe[data-src]');
      allIframes.forEach((iframe, i) => {
        const delay = Math.floor(Math.random() * 3000) + (3000 * i);
        setTimeout(() => {
          iframe.src = iframe.dataset.src;
        }, delay);
      });
    }

    window.addEventListener("load", () => {
      initBoxes();
      lazyLoadIframes();
      autoTriggerHoverScroll();
    });
  </script>
</body>
<style>
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
  body {
    font-family: sans-serif;
    background: #f9f9f9;
    padding: 4px;
    overflow: hidden;
  }
  .grid {
    display: grid;
    grid-template-columns: 1fr;
    gap: 2px;
  }
  .box {
    background: #fff;
    padding: 2px;
    border-radius: 6px;
    box-shadow: 0 0 4px rgba(0,0,0,0.1);
  }
  .box h4 {
    font-size: 10px;
    margin-bottom: 2px;
    text-align: center;
  }
  iframe {
    width: 100%;
    height: 30px;
    border: none;
    pointer-events: none;
    margin-bottom: 1px;
  }
</style>

</html>
